#!/usr/bin/env bash
#still the same thing

counter=1
while [ $counter -lt 21 ]; do
	case $counter in
		4)
			echo "bad luck from China"
			;;	
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
		*)
			echo "$counter"
	esac
	((counter++))
done
