#!/usr/bin/env bash

# Display content of the current directory
for file in *; do
    if [[ ! $file == .* ]]; then
        name_after_dash=$(echo "$file" | cut -d'-' -f2-)
        echo "$name_after_dash"
    fi
done
